name: Build, test and deloy

on:
  push:
    branches:
      - main

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'
      
      - name: Check dotnet version
        run: |
          dotnet --info

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    outputs: 
      status-message: ${{ steps.run-tests.outputs.status-message }}
    steps:
      - name: Run unit tests
        id: run-tests
        run: |
          echo "Running unit tests"
          echo "status-message=All tests passed" >> $GITHUB_ENV

  test-lint:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      status-message: ${{ steps.run-tests.outputs.status-message }}
    steps:
      - name: Checking lints
        id: run-tests
        run: |
          echo "Checking lints"
          echo "status-message=Lints testing passed" >> $GITHUB_ENV

  notify:
    runs-on: ubuntu-latest
    needs: [test-unit, test-lint]
    if: always()
    steps:
      - name: Notify
        run: |
          echo "Notifying about the build and test results"
          echo "Lint ==> ${{ needs.test-lint.result }}: ${{ needs.test-lint.outputs.status-message }}" 
          echo "Unit tests ==> ${{ needs.test-unit.result }}: ${{ needs.test-unit.outputs.status-message }}"

