name: DEV deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'DEV'
        type: environment

jobs:
  deploy-to-environment:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

  automation-tests:
    needs: deploy-to-environment
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deployed to ${{ needs.deploy-to-environment.outputs.deployment-url }}"
          echo "Running automation tests..."