name: Lint actions

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-docker:
    name: Docker action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Verify formatting
        uses: ./.github/actions/lint-docker

  lint-javascript:
    name: JavaScript action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Verify formatting
        uses: ./.github/actions/lint-javascript

  lint-javascript-alt:
    name: JavaScript action alternative
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json
      
      - name: Verify formatting
        uses: $/.github/actions/lint-javascript-alt

  lint-composite:
    name: Composite action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Verify formatting
        uses: ./.github/actions/lint-composite
